Arkschools\DataInputSheet\Bridge\Symfony\Entity\Cell:
  type: entity
  table: data_input_sheet_cell
  id:
    sheet:
      type: string
      column: sheet_id
    column:
      type: string
      column: column_id
    spine:
      type: string
      column: spine_id
  fields:
    type:
      type: smallint
      column: type
    contentInteger:
      type: integer
      column: content_integer
      nullable: true
    contentFloat:
      type: float
      column: content_float
      nullable: true
    contentString:
      type: text
      column: content_string
      nullable: true
