Arkschools\DataInputSheets\Bridge\Symfony\Entity\Cell:
  type: entity
  table: data_input_sheets_cell
  id:
    sheet:
      type: string
      column: sheet_id
    column:
      type: string
      column: column_id
    spine:
      type: string
      column: spine_id
  fields:
    type:
      type: smallint
      column: value_type
    contentBoolean:
      type: boolean
      column: value_bool
      nullable: true
    contentInteger:
      type: integer
      column: value_int
      nullable: true
    contentFloat:
      type: float
      column: value_float
      nullable: true
    contentString:
      type: string
      column: value_string
      nullable: true
    contentText:
      type: text
      column: value_text
      nullable: true
    contentDate:
      type: datetime
      column: value_datetime
      nullable: true
