parameters:
    data_input_sheets.entity_manager_name: default

services:
    arkschools.twig.data_input_sheets_cell:
        class: Arkschools\DataInputSheets\Bridge\Symfony\Twig\DataInputSheetsCellExtension
        tags:
            - { name: twig.extension }
